spring.application.name=DevCollabProject

# ============================================================
# DATABASE CONFIGURATION
# ============================================================

# JDBC URL of your MySQL database
spring.datasource.url=jdbc:mysql://localhost:3306/devcollabprojectdb

# Database username
spring.datasource.username=root

# Database password
spring.datasource.password=0000

# MySQL JDBC Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ============================================================
# JPA / HIBERNATE CONFIGURATION
# ============================================================

# Controls how Hibernate handles database tables
# none        -> Do nothing
# validate    -> Check if tables match entities
# update      -> Create/update tables without deleting data
# create      -> Drop existing tables and create new ones every startup
# create-drop -> Same as create, then drop tables when the application stops
spring.jpa.hibernate.ddl-auto=update

# Prints the generated SQL queries in the console
spring.jpa.show-sql=true

# Formats SQL queries to make them easier to read
spring.jpa.properties.hibernate.format_sql=true

# Specifies the SQL dialect Hibernate should use
# (Hibernate 6 usually detects this automatically, but keeping it is fine)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
